- name: Demo on simple playbook
  hosts: localhost
  connection: local
  tasks:
    - name: Task1
      ansible.builtin.debug:
        msg: 'Hello from Playbook Task1'
    - name: Task2
      ansible.builtin.debug:
        msg: 'Hello from Playbook Task2'

