- name: Demo on simple playbook
  hosts: localhost
  connection: local
  tasks:
    - name: upgrade all packages
      yum:
         name: '*'
         state: lates

    - name: install java
      yum:
        name: openjdk-11-jdk
        state: present

    - name: adding nexus user
      user:
        name: sonar
        state: present

    - name: downloading sonarqube
      ansible.builtin.unarchive:
        src: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt
        remote_src: yes